const mongoose =require('mongoose')
const materialSchema =mongoose.Schema({
    cementName:{
        type:String,
        required:true
    },
     cementQty:{
        type:Number,
        required:true
    },
     brickName:{
        type:String,
        required:true
    },
     brickQty:{
        type:Number,
        required:true
    },
     steelName:{
        type:String,
        require:true
    },
     steelQty:{
        type:Number,
        required:true
    },
    sandName:{
        type:String,
        required:true
    },
     sandQty:{
        type:Number,
        required:true
    },
    tileName:{
        type:String,
        required:true
    },
     tileQty:{
        type:Number,
        required:true
    },
    paintName:{
        type:String,
        required:true
    },
     paintQty:{
        type:Number,
        required:true
    },
    woodName:{
        type:String,
        required:true
    },
     woodQty:{
        type:Number,
        required:true
    },
    pvcpipeName:{
        type:String,
        required:true
    },
     pvcpipeQty:{
        type:Number,
        required:true
    },
    smId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"SiteManager"
    }
},{
    timestamps:true
})
module.exports=mongoose.model("material",materialSchema)